[package]
name = "mssql_tiberius_schema_parser"
version = "0.3.4"
edition = "2021"
readme = "README.md"
license = "MIT"
description = "Generates the schema of all tables in msql as a structure."
homepage = "https://github.com/rabbitson87/mssql_tiberius_schema_parser"
repository = "https://github.com/rabbitson87/mssql_tiberius_schema_parser"
documentation = "https://github.com/rabbitson87/mssql_tiberius_schema_parser"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
gethostname = "0.4.3"
tiberius = { version = "0.12.2", features = ["winauth", "chrono"] }
tokio = { version = "1.36.0", features = ["full"] }
tokio-util = { version = "0.7.10", features = ["full"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
strum = { version = "0.26.1", features = ["derive"] }
strum_macros = "0.26.1"
chrono = { version = "0.4.34", features = ["serde"] }

[profile.dev]
opt-level = 0

[profile.release]
strip = true
opt-level = "z"
codegen-units = 1
