instance_name = "JKSOFT"
user = "sa"
password = "crusher22betacharlie"
type = "ServerAuth"
use_split_file = true
path = "D:\\git\\JKPOS365_Windows_App\\native\\hub\\src\\helpers\\structs"
signal_path = "D:\\git\\JKPOS365_Windows_App\\native\\hub\\src\\signals"

[database]
use_import_special = true
split_directory = [
    { starts_with_name = "jkrtdb", directory_name = "jk_restaurant" },
    { starts_with_name = "jkttdb", directory_name = "jk_retail" },
]
tables = [
    { table_name = "jkrtdb_dbo_rcategory", use_signal_parser = true },
    { table_name = "jkrtdb_dbo_ritem", use_signal_parser = true },
    { table_name = "jkrtdb_dbo_rpricegroup", use_signal_file = false },
    { table_name = "jkrtdb_dbo_rreference", use_signal_parser = true },
    { table_name = "jkrtdb_dbo_rstore", use_signal_file = false },
    { table_name = "jkrtdb_dbo_rtable", use_signal_file = false },
    { table_name = "jkrtdb_dbo_rtablesection", use_signal_file = false },
    { table_name = "jkrtdb_dbo_rupcharge", use_signal_parser = true },
    { table_name = "jkrtdb_dbo_rupchargegroup", use_signal_parser = true },
    { table_name = "jkrtdb_dbo_saction", use_signal_file = false },
    { table_name = "jkrtdb_dbo_seditinginvoice", use_signal_file = false },
    { table_name = "jkrtdb_dbo_sidentity", use_signal_file = false },
    { table_name = "jkrtdb_dbo_smessage", use_signal_file = false },
    { table_name = "jkrtdb_dbo_spreference", use_signal_parser = true },
    { table_name = "jkrtdb_dbo_sdictionary", use_signal_parser = true },
    { table_name = "jkrtdb_dbo_tinvoice", use_signal_file = false },
    { table_name = "jkrtdb_dbo_titem", use_signal_file = false },
    { table_name = "jkrtdb_dbo_tupcharge", use_signal_file = false },
    { table_name = "jkttdb_dbo_ritem", use_signal_parser = true },
    { table_name = "jkttdb_dbo_rlist", use_signal_file = false },
    { table_name = "jkttdb_dbo_rpromotion", use_signal_file = false },
    { table_name = "jkttdb_dbo_rpromotionitem", use_signal_file = false },
    { table_name = "jkttdb_dbo_rstore", use_signal_file = false },
    { table_name = "jkttdb_dbo_temployee", use_signal_file = false },
    { table_name = "jkttdb_dbo_ttimeclock", use_signal_file = false },

]
